DROP DATABASE IF EXISTS dbgarage;
CREATE DATABASE dbgarage;
USE dbgarage;

CREATE TABLE customer(
idcust BIGINT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
username VARCHAR(30) NOT NULL UNIQUE,
pw VARCHAR(30) NOT NULL,
fullname VARCHAR(100) NOT NULL,
email VARCHAR(50) NOT NULL, 
phonenum VARCHAR(20) NOT NULL,
adminaccess BOOL NOT NULL
);

CREATE TABLE vehicle(
idveh BIGINT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
idcust BIGINT NOT NULL,
FOREIGN KEY (idcust) REFERENCES customer(idcust) ON DELETE CASCADE,
vehicle_type VARCHAR(50) NOT NULL,
vehicle_make VARCHAR(30) NOT NULL,
vehicle_engine_type VARCHAR(30) NOT NULL,
vehicle_license VARCHAR (20) NOT NULL
);

CREATE TABLE mech(
idmech BIGINT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
namemech VARCHAR(20)
);

CREATE TABLE appointment(
idap BIGINT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
service TINYINT ,
dateap DATETIME NOT NULL,
cmt VARCHAR(200),
price DOUBLE ,
addcost DOUBLE,
state VARCHAR(15) NOT NULL,
idcust BIGINT NOT NULL,
FOREIGN KEY (idcust) REFERENCES customer(idcust) ON DELETE CASCADE
);

CREATE TABLE mechschedule(
idsched BIGINT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
idmech BIGINT ,
idap BIGINT ,
FOREIGN KEY (idmech) REFERENCES mech(idmech) ON DELETE SET NULL,
FOREIGN KEY (idap) REFERENCES appointment(idap) ON DELETE CASCADE
);

CREATE TABLE items(
idsup BIGINT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
nameitem VARCHAR(20),
price DOUBLE NOT NULL
);
